### ISSUE TITLE
Configure different HEC destinations

### ISSUE THREAD

**Issue by ivanfr90** [splunk/splunk-connect-for-snmp#1082]
Hi.

We have a SC4SNMP instance on a K8S arquitecture configured for traps and polling. Also we hace several Heavy Forwarders and we need to send traps to a specific Heavy Forwarder and polling events and metrics to other Heavy Forwarder. It's possible create some type of redirection based on this specific configuration? 

Our approach right now is to execute an instance of SC4SNMP only for traps and another instance of SC4SNMP for polling. Each of this instances send data to a specific Heavy Forwarder. Could you suggest some kind of alternative architecture?

Thanks!

**Comment by ikheifets-splunk** [comment]
On call with discussed with @ivanfr90 that they need to segregate `polling/walks` logs to one Splunk, and `traps` to another Splunk. 

We discussed to use for that [Splunk Edge Processor](https://www.splunk.com/en_us/blog/platform/introducing-edge-processor-next-gen-data-transformation.html), but SPL2 not enough powerful and they wanna use [vector](https://opensource.datadoghq.com/projects/vector/) that have support of Lua for implement complex pipelines.

Proposed workaround:
* Use seperaed SC4SNMP instances, one of that will report only `poll/walks` to `vector` (using HEC adapter), second one will report only `traps` will go to `Splunk`.
* Consume all logs in `vector` and my different branch of logic for logs with sourcetype `sc4snmp:traps` / `sc4snmp:event` / `sc4snmp:metric`.

P.S. @ivanfr90 If I miss something or you have any question, please reopen this issue
