### ISSUE TITLE
sim subchart does not support nodeSelector in deployment

### ISSUE THREAD

**Issue by berryfl** [splunk/splunk-connect-for-snmp#1093]
In the GKE clusters I manage, there are a few node pools for different applications. I want to install all the sc4snmp components into one specific node pool.

Currently, I find that most components already support `nodeSelector` in the deployments, such as `scheduler`, `traps`, `worker`, as well as the dependencies redis, mongodb and mibserver. However, `sim` component seems not support `nodeSelector` yet in the deployment when I read the chart source code.

**Comment by ajasnosz** [comment]
Hello @berryfl, you can find updated chart in version 1.12.0-beta.4
