### ISSUE TITLE
Pre-releases are being published in Releases

### ISSUE THREAD

**Issue by dgcom** [splunk/splunk-connect-for-snmp#176]
Hi!

Is there any specific reason that pre-releases of v0.11 are being published in releases section of the repository multiple times a day?
It is up to v0.11.0-next.38 right now...This triggers GitHub release notification every time - which it shouldn't because these are not real releases as far as I can tell. 
Something is mis-configured and makes it impossible to watch this project for actual releases.

**Comment by rfaircloth-splunk** [comment]
These are all market "pre-release" I don't know why the GH notifier is pushing notifications on pre-release versions

**Comment by dgcom** [comment]
Hi!

I follow many repositories and spunk-connect-for-snmp seems to be the only one breaking this way...
I understand, that these are marked as pre-release, but regardless - they show up as release notifications - very annoying.
Even that they are labeled as "Pre-release", they show up in the release [section here](https://github.com/splunk/splunk-connect-for-snmp/releases).

![image](https://user-images.githubusercontent.com/7088388/143732045-667c43b9-331e-43a9-b46d-7827688e7d9c.png)

There is something misconfigured here, unfortunately I am not an expert in GitHub to help fixing it.

**Comment by rfaircloth-splunk** [comment]
Sorry not sure how to help other than suggest contating github a notification filter would be a nice filter.

**Comment by dgcom** [comment]
I looked at the docs - GitHub treats pre-releases same way as releases, identification as pre-release is "_To notify users that the release is not ready for production and may be unstable_".
I really don't understand why would you publish 5 releases a day, even marking them unstable? This doesn't make much sense.
The project page is now showing that there are 109 releases, blowing up and skewing project statistics as well...
