### ISSUE TITLE
[Test] Performance Tests - Measure machine resource utilisation 

### ISSUE THREAD

**Issue by pszkamruk-splunk** [splunk/splunk-connect-for-snmp#22]
As a developer I would like to know how much of resources SNMP connector uses in terms of different load characteristics

AC: 
Measure mapping between traps, gets and walk and machine resources.

**Comment by matthewmodestino** [comment]
as a general piece of feedback, the number of traps per second I have seen quoted from big shops running snmptrapd with custom handlers is ~2-2.5K traps per second per trap server instance, in case you wanted an anecdotal number as we prep for tests.

**Comment by pszkamruk-splunk** [comment]
Hi @matthewmodestino 
Do you have also any recommendations regarding how many gets are configured in customer system? 
Thanks

**Comment by matthewmodestino** [comment]
Ah yeah, sorry had traps on the mind.

For polling i always went with distributed Cacti pollers and would achieve ~100k unique "data sources" where "data sources" map loosely to "GETs"

https://github.com/n00badmin/mirage/issues/10#issuecomment-356939442

Here's some history for ya :)

This is outlining plugin that I built into cacti that is still in use in the wild at some large customers.
