### ISSUE TITLE
Add to the docs some information about opening relevant ports when doing clustering

### ISSUE THREAD

**Issue by jefair2** [splunk/splunk-connect-for-snmp#282]
Would point to the following doc link from mk8s from one of the sections talking about setting up clustering that you need to make sure any of the listed "host interfaces" in this list need to be allowed through the firewalls and such. As the list is quite lengthy and wasn't entirely obvious what all ports are getting used until we dug into the documentation of microk8s, so this would save someone else the same headaches, because the errors thrown by mk8s doesn't make it super clear it is a port issue.

Might also be worth starting a "troubleshooting" section as well with this as one of the things to double check.

https://microk8s.io/docs/ports

**Comment by rfaircloth-splunk** [comment]
Good point, I believe your deployment was on RHEL7, on Ubuntu and Rhel 8 the install was able to open ports on its own I but I don't think this works on rhel 7

**Comment by jefair2** [comment]
Yes, this was RHEL 7.

**Comment by aryznar-splunk** [comment]
Added in documentation, so far it is in develop branch but when merge happen to main it will be also in main: https://splunk.github.io/splunk-connect-for-snmp/develop/bestpractices/#installing-splunk-connect-for-snmp-on-linux-redhat
