### ISSUE TITLE
Documentation updates needed for Splunk Infrastructure Monitoring 

### ISSUE THREAD

**Issue by jelkhouri-splunk** [splunk/splunk-connect-for-snmp#335]
On the [Splunk Requirements Page](https://splunk.github.io/splunk-connect-for-snmp/main/gettingstarted/splunk-requirements/), in the Splunk Infrastructure Monitoring section, you almost miss the instructions because it's so short. Perhaps better to state: 
Obtain the following from your Splunk Observability Cloud environment: 
1. Realm
2. Token

On the [Splunk Connect for Kubernetes page](https://splunk.github.io/splunk-connect-for-snmp/main/gettingstarted/sck-installation/), this is very confusing: 
"To learn more about SCK visit. Including configuration with Splunk Observability Cloud."

On that same page, there should be a box for O11y that contains
microk8s helm3 upgrade --install sck \
  --set="clusterName=rakuten_test_cluster" \
  --set="splunkObservability.realm=<realm>" \
  --set="splunkObservability.accessToken=<token>" \
  --set="splunkObservability.ingestUrl=https://ingest.<realm>.signalfx.com" \
  --set="splunkObservability.apiUrl=https://api.<realm>.signalfx.com" \
  --set="splunkObservability.metricsEnabled=true" \
  --set="splunkObservability.tracesEnabled=false" \
  --set="splunkObservability.logsEnabled=false" \
  splunk-otel-collector-chart/splunk-otel-collector

On that same page, in the variables description section, a variables description for O11y should be added that has the realm and token

Also, In the Poller section of the yaml, if using O11y, poller usernameSecrets needs to be uncommented and set to blank
poller.usernameSecrets: {}

**Comment by jelkhouri-splunk** [comment]
Hello! Thank you so much for the updates to the docs. I don't see this update, however: 
Also, In the Poller section of the yaml, if using O11y, poller usernameSecrets needs to be uncommented and set to blank
poller.usernameSecrets: {}
On [this page](https://splunk.github.io/splunk-connect-for-snmp/main/gettingstarted/sc4snmp-installation/).

**Comment by omrozowicz-splunk** [comment]
Hi! 
I didn't include `poller.usernameSecrets: {}` in the documentation, because we fixed it from inside of Helm chart in commit https://github.com/splunk/splunk-connect-for-snmp/commit/6207c6fe271365d9fc647342fa9d60fd9d763f54. It should work fine now even without uncommenting that line.
Btw, thank you for your tips about the documentation, we appreciate it very much 😃

**Comment by jelkhouri-splunk** [comment]
Awesome! Thank you!
