### ISSUE TITLE
Metallb on Cloud

### ISSUE THREAD

**Issue by polarG** [splunk/splunk-connect-for-snmp#400]
I am not sure if this is an issue, just call out here.

In the deployment, microk8s use metallb to do the LB for traps. And from the documentation of metallb, it's for bare-metal cluster since it's a layer 2 LB. https://metallb.universe.tf/installation/clouds/
 
So my question is:
In multi-node deployment, can microk8s with metallb work on public cloud suppler? liking using EC2?
No matter it works or not, I think we need more details about this on the release doc or user manual.

Thanks

**Comment by polarG** [comment]
And in the traps/service.yaml, externalTrafficPolicy is set to Local. Is this mean the external traffic will only be forwarded to the local node, rather than cluster?

**Comment by omrozowicz-splunk** [comment]
Hi, we built a beta version where `externalTrafficPolicy` is exposed, to run it use:
```
image:
  tag: "1.5.8-beta.1"
  pullPolicy: "Always"
```
and under traps:
```
traps:
  service:
    externalTrafficPolicy: Cluster
```

**Comment by omrozowicz-splunk** [comment]
We use MetalLB as an LB for SC4SNMP installation because in most of the real-life scenarios it will be installed on a bare-metal infrastructure. SNMP is a protocol used mainly on legacy devices, so it would be unusual to have a cloud environment as a point of the management.

**Comment by polarG** [comment]
Thanks, that make sense.
