### ISSUE TITLE
scheduler crash

### ISSUE THREAD

**Issue by polarG** [splunk/splunk-connect-for-snmp#436]
Version: 1.5.9
Reproducible: yes
Config: refer to attachment
Logs: refer to attachment

[scheduler-log.txt](https://github.com/splunk/splunk-connect-for-snmp/files/8313330/scheduler-log.txt)
[snmp-values.yaml.txt](https://github.com/splunk/splunk-connect-for-snmp/files/8313331/snmp-values.yaml.txt)

**Comment by omrozowicz-splunk** [comment]
Hey! 
Can you provide more details about the condition when it happened?
Did it happen after you added more lines to the inventory? Have you had any working version before on the same environment? 
Have you configured anything new when it crashed? 
Does it happen every time you reinstall SC4SNMP?

**Comment by polarG** [comment]
1.  When it happened. 
5~10 mins after the sc4snmp started.
2. Did it happen after you added more lines to the inventory? Have you had any working version before on the same environment?
Yes, and the last working version have less lines in inventory and only 1 worker pod.
3. Have you configured anything new when it crashed?
Yes, worker pod number changed to 2 (pervious working version with 1 worker)
4. Does it happen every time you reinstall SC4SNMP?
Yes, it is reproducible.
