### ISSUE TITLE
Helm chart - broken configmap requirement

### ISSUE THREAD

**Issue by stefanjay** [splunk/splunk-connect-for-snmp#533]
Hello there,

during the deployment on `mk8s` using the *current* helm3 chart (see below *1) a pod is stucked and cannot start.

*1
```
❯ helm search repo snmp
NAME                                           	CHART VERSION	APP VERSION	DESCRIPTION
splunk-connect-for-snmp/splunk-connect-for-snmp	1.7.0        	1.7.0      	A Helm chart for SNMP Connect for SNMP
```

### actual "bug"
- the pod `snmp-splunk-connect-for-snmp-inventory` is stuck in status:
```
snmp-splunk-connect-for-snmp-inventory-pftnm                  0/1     ContainerCreating   0          12m
```
#### root cause:
- the `configmap` for the inventory is missing the `inventory.csv` file. 

### workaround
deletion of the `configmap` and recreation with an empty inventory.csv and deletion of the pod:

```
touch inventory.csv && kubectl -n sc4snmp create cm --from-file=inventory.csv
```

### question
why is the inventory pod been deleted after the installation process?

**Comment by omrozowicz-splunk** [comment]
Hello,
Thanks for reporting it!
This issue appears when `poller.inventory` part is commented out, so when no polling is used in SC4SNMP. The `inventory.csv` file is created from `poller.inventory` part, and looks like the inventory job can't read up the default value (still investigating it). Inventory pod/job serves only for polling purposes, so there is to option for you there:
