### ISSUE TITLE
helm chart - traps service should have support for annotations

### ISSUE THREAD

**Issue by minhnhupham** [splunk/splunk-connect-for-snmp#572]
The Traps service which is created by the helm chart should support annotations so various settings can be configured on different k8s platforms. (e.g. GCP GKE, Azure AKS, AWS EKS, etc...)
Right now there's no way to tweak various settings using annotations for the Trap service that gets created.
https://github.com/splunk/splunk-connect-for-snmp/blob/main/charts/splunk-connect-for-snmp/templates/traps/service.yaml

e.g. If SC4SNMP was deployed on a GKE cluster the traps service would be configured with an external loadbalancer with an external public internet IP address, this may/may not be a desired configuration, but right now there's no way to tweak this with annotations.
An example of this: 
https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#create

Annotation support actually should be added to all other services in the helm chart as well, since this appears to be missing.

**Comment by omrozowicz-splunk** [comment]
Hello, the change you requested was released in [1.8.2-beta.1](https://github.com/orgs/splunk/packages/container/splunk-connect-for-snmp%2Fcontainer/42602830?tag=1.8.2-beta.1). We added two ways of configuring annotations:
1. [under the service](https://splunk.github.io/splunk-connect-for-snmp/develop/configuration/trap-configuration/#define-annotations)
2. [as a common annotation, adds annotation to every service](https://splunk.github.io/splunk-connect-for-snmp/develop/configuration/deployment-configuration/)

You can test it using [upgrading to specific version](https://splunk.github.io/splunk-connect-for-snmp/develop/upgrade/#upgrade-to-a-specific-version) instruction. Please let me know if it solves the issue, then it will be included in the main release.
Thanks!

**Comment by minhnhupham** [comment]
Great thanks.
We've this for the traps service and seems to work correctly.
