### ISSUE TITLE
Still waiting for redis://snmp-redis-headless:6379/0

### ISSUE THREAD

**Issue by grywicks** [splunk/splunk-connect-for-snmp#629]
Inventory log return this : Still waiting for redis://snmp-redis-headless:6379/0
When I list pods associated with my workspace : 

![Capture](https://user-images.githubusercontent.com/115655710/195404786-e0dc1198-316d-4234-8c27-14fd619d911e.PNG)

I didn't see the snmp-redis-master-0 in the list ... I double checked my value.yaml file but impossible to understand why this pod doesn't appear in the list ... Can somebody help me with this problem ?

**Comment by wojtekzyla** [comment]
Hi, could you send status of the pods `microk8s kubectl get pods -A` to check if all of the addons work and also list of all deployments `microk8s kubectl get deployments -A`.

**Comment by grywicks** [comment]
Hi, 
`microk8s kubectl get pods -A` :
![Capture](https://user-images.githubusercontent.com/115655710/195557422-13f26161-277d-49ef-bdc5-b97ec8fb7b98.PNG)

`microk8s kubectl get deployments -A` :
![Capture2](https://user-images.githubusercontent.com/115655710/195557843-2bc9e3e9-66fb-41f8-8404-09b1789c4754.PNG)

Thank's for your help !

**Comment by omrozowicz-splunk** [comment]
Hello, thanks for sending the logs. Would be helpful to additionally have the output of `microk8s kubectl get all -n sc4snmp` (Redis should appear as a stateful set) and maybe `microk8s kubectl get events -n sc4snmp ` (we're especially interested in ERRORs and WARNINGs).
