### ISSUE TITLE
Helm template for Traps pod failing to pull secrets

### ISSUE THREAD

**Issue by minhnhupham** [splunk/splunk-connect-for-snmp#641]
Hi,
The current helm template for trap agent appear to be using the helm **lookup** function to perform secret lookups.
Ref:
https://github.com/splunk/splunk-connect-for-snmp/blob/v1.8.4/charts/splunk-connect-for-snmp/templates/traps/deployment.yaml#L140

This won't work when this helm template is used on systems that doesn't use the helm cli to deploy. e.g. ArgoCD, FluxCD, etc...
Because these GitOps base solutions are rendering the templates ahead of time before applying the manifest objects.
This is a similar issue to the one I raised previously for the poller agents template.
https://github.com/splunk/splunk-connect-for-snmp/issues/613

Can this be fixed the same way as the one done for the poller agent template in the issue mentioned above?

Thanks,

**Comment by omrozowicz-splunk** [comment]
Hey, you can test if it works correctly now using version [1.8.5-beta.1](https://github.com/splunk/splunk-connect-for-snmp/releases/tag/v1.8.5-beta.1)
