### ISSUE TITLE
DNS resolution

### ISSUE THREAD

**Issue by are0002** [splunk/splunk-connect-for-snmp#712]
It will be nice to have DNS entries for the inventory instead of using just IP Address. If we can have DNS entries and DNS resolution it will solve some "dynamic" ip address scenarios.

**Comment by omrozowicz-splunk** [comment]
Hey, it was released as a part of `1.9.0` version.
This is how to upgrade: https://splunk.github.io/splunk-connect-for-snmp/main/upgrade/
