### ISSUE TITLE
Fault tolerant / redundancy?

### ISSUE THREAD

**Issue by LarsFromMars** [splunk/splunk-connect-for-snmp#730]
The SC4SNMP is stated as a highly available solution - is this on a single host?
Can it be scaled onto several hosts - like a cluster?
How would the solution share the config in a yaml file so not to have duplicate data?
Thx

**Comment by omrozowicz-splunk** [comment]
Hey, yes, you can deploy it in a [Kubernetes cluster](https://splunk.github.io/splunk-connect-for-snmp/main/gettingstarted/mk8s/k8s-microk8s/#add-additional-nodes-optional). But there is a single point that schedules polling tasks (the scheduler), so we have one place where the data is being kept. In a multinode cluster after the helm installation the pods will be deployed on different nodes, but will be subscribed to a single scheduler. Not sure though if this is what you meant in the question.

**Comment by LarsFromMars** [comment]
That link goes to adding an extra node - on the same host - what if the host that runs mickrok8 fails or is unavailable? - is there a way to have different hosts on different availability zones (eg: 2a, 2b 2c)
Something like this : https://dev.to/afeiszli/how-to-deploy-a-cross-cloud-kubernetes-cluster-with-built-in-disaster-recovery-3h36
But how then do we ensure we are not polling the same devices from all hosts in the cluster?

**Comment by omrozowicz-splunk** [comment]
So if this is the question, then no - there's no option to run it on a distributed cluster (sorry for misunderstanding, I thought you mean a multinode cluster at first). The only option to run it on a different hosts on different availability zones is to just deploy cluster with SC4SNMP on each of them and configure with only the hosts from each site. There's no mechanism of config management for a multi-cluster.
