### ISSUE TITLE
pods stuck in terminating state

### ISSUE THREAD

**Issue by LarsFromMars** [splunk/splunk-connect-for-snmp#736]
I have tried to stop and uninstall snmp and re-install but i am stuck in this state..

> NAME                                                          READY   STATUS        RESTARTS   AGE
snmp-mibserver-68665c8f55-shhz2                               1/1     Terminating   0          14d
snmp-redis-master-0                                           1/1     Terminating   0          14d
snmp-splunk-connect-for-snmp-worker-sender-847c9dbd95-v9458   1/1     Terminating   0          14d
snmp-mongodb-57d7cdf5f6-74t26                                 2/2     Terminating   0          14d
snmp-splunk-connect-for-snmp-worker-poller-77cbfc4555-nnbgk   1/1     Terminating   0          14d
snmp-splunk-connect-for-snmp-worker-poller-77cbfc4555-mj5sp   1/1     Terminating   0          14d
snmp-splunk-connect-for-snmp-trap-54676c6d6f-b5qpw            1/1     Terminating   0          14d
snmp-splunk-connect-for-snmp-trap-54676c6d6f-zv2k9            1/1     Terminating   0          14d
snmp-splunk-connect-for-snmp-scheduler-58d89d4dc9-777d2       1/1     Terminating   0          14d
snmp-splunk-connect-for-snmp-worker-trap-799cb7bb59-mbbcl     1/1     Terminating   0          14d
snmp-splunk-connect-for-snmp-worker-trap-799cb7bb59-rqp2g     1/1     Terminating   0          14d

**Comment by LarsFromMars** [comment]
I have tried:

># microk8s helm3 uninstall snmp -n sc4snmp
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/5137/credentials/client.config
Error: uninstall: Release not loaded: snmp: release: not found
>
and also ..
># microk8s helm3 uninstall snmp -n sc4snmp
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/5137/credentials/client.config
Error: uninstall: Release not loaded: snmp: release: not found
>

but it just hangs
Also a reboot did not resolve issue

**Comment by LarsFromMars** [comment]
OK fixed it .. i thought but still broken .. i was able to kill the pods with:
`microk8s kubectl delete pod snmp-splunk-connect-for-snmp-trap-54676c6d6f-b5qpw --grace-period=0 --force --namespace sc4snmp` 
until i got:
`microk8s kubectl delete pod snmp-splunk-connect-for-snmp-trap-54676c6d6f-b5qpw --grace-period=0 --force --namespace sc4snmp`
But now when i try and re-install snmp - only 4 pods start .. 
`
microk8s kubectl get pods -n sc4snmpNAME                                                         READY   STATUS    RESTARTS   AGE
snmp-splunk-connect-for-snmp-worker-sender-6f9d97567-qk5nv   0/1     Pending   0          15s
snmp-mibserver-68665c8f55-5lw2c                              0/1     Pending   0          15s
snmp-mongodb-76c9f55486-c7w4b                                0/2     Pending   0          15s
snmp-redis-master-0                                          0/1     Pending   0          15s
`

**Comment by LarsFromMars** [comment]
Even after un-installing sc4snmp and removing and snap installing microk8s again i still now only see 4 pods running ..

`
# microk8s kubectl get pods -n sc4snmp
NAME                                                          READY   STATUS    RESTARTS   AGE
snmp-mongodb-6df549cfd5-jgggb                                 0/2     Pending   0          10m
snmp-redis-master-0                                           0/1     Pending   0          10m
snmp-splunk-connect-for-snmp-worker-sender-7f644bcd78-rt2n9   1/1     Running   0          10m
snmp-mibserver-847c5bf574-g488k `

**Comment by omrozowicz-splunk** [comment]
Isn't it a problem with not enough resources?
Can you check `microk8s kubectl get events -A` and `microk8s describe nodes`?

**Comment by LarsFromMars** [comment]
> 

this is a c6i.2xlarge | 8cpu | 16GB

` microk8s kubectl get events -A
NAMESPACE   LAST SEEN   TYPE      REASON                    OBJECT                                                 MESSAGE
sc4snmp     4m55s       Normal    FailedBinding             persistentvolumeclaim/snmp-mongodb                     no persistent volumes available for this claim and no storage class is set
sc4snmp     4m55s       Normal    FailedBinding             persistentvolumeclaim/redis-data-snmp-redis-master-0   no persistent volumes available for this claim and no storage class is set
sc4snmp     4m35s       Warning   FailedGetResourceMetric   horizontalpodautoscaler/snmp-mibserver                 failed to get memory utilization: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)`

` microk8s describe nodes
'describe' is not a valid MicroK8s subcommand.`

**Comment by LarsFromMars** [comment]
> microk8s status --wait-ready
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm                 # (core) Helm - the package manager for Kubernetes
    helm3                # (core) Helm 3 - the package manager for Kubernetes
    metallb              # (core) Loadbalancer for your Kubernetes cluster
  disabled:
    cert-manager         # (core) Cloud native certificate management
    community            # (core) The community addons repository
    dashboard            # (core) The Kubernetes dashboard
    gpu                  # (core) Automatic enablement of Nvidia CUDA
    host-access          # (core) Allow Pods connecting to Host services smoothly
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    ingress              # (core) Ingress controller for external access
    kube-ovn             # (core) An advanced network fabric for Kubernetes
    mayastor             # (core) OpenEBS MayaStor
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    observability        # (core) A lightweight observability stack for logs, traces and metrics
    prometheus           # (core) Prometheus operator for monitoring and logging
    rbac                 # (core) Role-Based Access Control for authorisation
    registry             # (core) Private image registry exposed on localhost:32000
    storage              # (core) Alias to hostpath-storage add-on, deprecated

**Comment by omrozowicz-splunk** [comment]
Okay, I see your `hostpath-storage` is disabled, an the error communicate is  `no persistent volumes available for this claim and no storage class is set sc4snmp`. Can you run `microk8s enable hostpath-storage`? Then you can check for available stroageclasses on your kubernetes cluster with `microk8s kubectl get storageclass`

**Comment by LarsFromMars** [comment]
Thanks - thats sorted it.

> ran that command and then unistalled snmp and re-installed and looks a lot better.

> microk8s kubectl get pods -n sc4snmp
NAME                                                          READY   STATUS      RESTARTS   AGE
snmp-mibserver-847c5bf574-q9wxt                               1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-worker-trap-c944fbd96-cf8gm      1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-worker-sender-85bb6df4bd-5vxq5   1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-trap-dfc6687f4-t424c             1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-trap-dfc6687f4-qhjkr             1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-scheduler-7bc4f57cdb-vnf6h       1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-worker-trap-c944fbd96-k2jkz      1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-worker-poller-6b9c8c656d-7gbns   1/1     Running     0          5m42s
snmp-splunk-connect-for-snmp-worker-poller-6b9c8c656d-66ztj   1/1     Running     0          5m42s
snmp-redis-master-0                                           1/1     Running     0          5m42s
snmp-mongodb-75b89b595f-r9jr6                                 2/2     Running     0          5m42s
snmp-splunk-connect-for-snmp-inventory-6rlvv                  0/1     Completed   0          5m42s

thanks

**Comment by omrozowicz-splunk** [comment]
No problem, closing it.

**Comment by omrozowicz-splunk** [comment]
No problem, closing it.
