### ISSUE TITLE
Some "metrics" being reported as dimensions

### ISSUE THREAD

**Issue by M-Bates** [splunk/splunk-connect-for-snmp#918]
A number of data types that are the same as Gauge or Counter are currently being extracted as dimensions rather than metrics.
The data types are defined in the IETF textual conventions files, HCNUM-TC

- CounterBasedGauge64
- ZeroBasedCounter64

![Screenshot 2023-11-17 111421](https://github.com/splunk/splunk-connect-for-snmp/assets/87510651/a4e055a1-e54e-4bd9-ad50-37d34a93cea5)

**Comment by ajasnosz** [comment]
The values you mention as `CounterBasedGauge64` are `jnxJsNodeSessionCreationPerSecond` and ` jnxJsNodeSessCreationPerSecIPv4` in this mib, I don't see any ZeroBasedCounter64, are there any of this type? Were they presented as metrics before? Could you show how they look like without using sc4snmp?

**Comment by M-Bates** [comment]
The values for the 3 CounterBasedGuauge64 from the Juniper MIB has always been interpreted as a dim rather than metric

-    jnxJsNodeSessCreationPerSecIPv4: 13
-    jnxJsNodeSessCreationPerSecIPv6: 0
-    jnxJsNodeSessionCreationPerSecond: 13


snmpget -v 2c -c <<community>> -m +JUNIPER-SRX5000-SPU-MONITORING-MIB <<host>>.1.3.6.1.4.1.2636.3.39.1.12.1.4.1.5.0
JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsNodeSessionCreationPerSecond.0 = Counter64: 3

Unfortunately, these are the only 3 CounterBasedGuage metrics being collected across all device types.

**Comment by ajasnosz** [comment]
If they were always interpreted as dim then it is what we expect, as this depends on mib and pysnmp library. We don't have any exceptions that we apply when translating, it's all automatically translated.

**Comment by M-Bates** [comment]
I cannot tell you whether they were always wrong.
What I can say is that they are wrong now, and need to be correctly sent as metric points not dimensions. This is also a function of this library, not pysnmp.

As requested, please fix the issue with the 2 data types being sent as dimensions rather than metric values.
This is a breaking issue as there is no way to consistently graph the values of dimensions over time for large volumes of data.

**Comment by ajasnosz** [comment]
@M-Bates did you have time to test above image?

**Comment by M-Bates** [comment]
Not as yet. The customer has been in a change freeze. I should the ability to test it around mid-Jan.

**Comment by ajasnosz** [comment]
@M-Bates was the image tested and is working fine?

**Comment by M-Bates** [comment]
Hi,

I no longer have access to be able to test this.
As the changes required are part of standard MIBS, not just Juniper specific, the changes should be testable and verifiable by the product owner.

Failure of the product to correctly represent standard MIB data types is a fundamental failure in the product.


Michael Bates

Principal Consultant

Mobile +61 411 440 095 · Phone (03) 9880 5528

Level 35, 80 Collins Street, Melbourne, VIC 3000, Australia · tesserent.com<https://tesserent.com/>

[Tesserent]

Follow Us [Linkedin] <https://www.linkedin.com/company/tesserent/> [Youtube] <https://www.youtube.com/channel/UC5SpXfc8EGshynZ3QSZYz_w>

________________________________
