### ISSUE TITLE
Worker sender logs

### ISSUE THREAD

**Issue by sebs04** [splunk/splunk-connect-for-snmp#941]
Hi, 

In the worker sender logs I only see logs when the trap is correct. I have tried with the log level in DEBUB, WARNING, ERROR, CRITICAL and FATAL and nothing.

The idea is that for example, if I am using snmp in version 3 and I make a mistake in the user password or in some character of that relevance to be able to have visibility at log level.

**Comment by ajasnosz** [comment]
Hello,
In code we have listeners, that are configured to only catch calls that match the configuration. With this set up the misconfigured calls are dropped, so you can't see any log.

**Comment by sebs04** [comment]
Hi, 

Thanks for the reply, I have one more question about this issue. I understand that even if I use a tcpdump inside the pod it will not show the misconfigured calls due to the fact that it is dropped by the sc4snmp code right?

**Comment by ajasnosz** [comment]
Hello,
Yes, I would say you have the right conclusions and it won't be visible.

**Comment by ajasnosz** [comment]
Issue was solved in release 1.10 for traps and pollers. To see the documentation about possible errors and their meaning you can check [troubleshooting section](https://splunk.github.io/splunk-connect-for-snmp/main/bestpractices/#identifying-traps-issues). Documentation about poller will be available from v1.11.
